### This is the Terraform-generated dev-build.yml workflow for the oai-pmh-harvester-dev app repository ###
name: dev Build and Deploy Fargate Container
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  deploy:
    name: dev Deploy Fargate Container
    uses: mitlibraries/.github/.github/workflows/fargate-shared-deploy-dev.yml@container-flows
    secrets: inherit
    with:
      AWS_REGION: "us-east-1"
      GHA_ROLE: "oai-pmh-harvester-gha-dev"
      ECR: "oai-pmh-harvester-dev"
