name: Test
on: push
jobs:
  test:
    name: Run tests and send to coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64
      - name: Install
        run: |
          python -m pip install --upgrade pip pipenv
          make install

      - name: Run tests and make coverage report
        run: make coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev

      - name: Lint
        run: make lint